name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

      - run: esy install 
      - run: esy b dune build
      - run: esy b dune runtest